cd Images\Logos\Large\1
call PACK.BAT
cd ..\2
call PACK.BAT
cd ..\3
call PACK.BAT
cd ..\4
call PACK.BAT
cd ..\5
call PACK.BAT
cd ..\6
call PACK.BAT
cd ..\7
call PACK.BAT
cd ..\8
call PACK.BAT
cd ..\9
call PACK.BAT
cd ..\10
call PACK.BAT
cd ..\11
call PACK.BAT

cd ..\..\small\1
call PACK.BAT
cd ..\2
call PACK.BAT
cd ..\3
call PACK.BAT
cd ..\4
call PACK.BAT
cd ..\5
call PACK.BAT
cd ..\6
call PACK.BAT
cd ..\7
call PACK.BAT
cd ..\8
call PACK.BAT
cd ..\9
call PACK.BAT
cd ..\10
call PACK.BAT
cd ..\11
call PACK.BAT

cd ..\..\..\persons
call PACK.BAT

cd ..\products
call PACK.BAT

cd ..\..
LibResDir FileList.txt CAPMOD.RES
